# Generated by Django 4.1 on 2022-10-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labSoft3", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_factura", models.CharField(max_length=200)),
                ("fecha_factura", models.CharField(max_length=200)),
                ("nombre_cliente", models.CharField(max_length=200)),
                ("producto", models.CharField(max_length=200)),
                ("nit_empresa", models.CharField(max_length=200)),
                ("cantidad", models.CharField(max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=9)),
                ("precio_total", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_mesa", models.IntegerField()),
                ("cantidad_Sillas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_producto", models.CharField(max_length=200)),
                ("nombre", models.CharField(max_length=200)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_reserva", models.CharField(max_length=200)),
                ("numero_mesa", models.IntegerField()),
                ("tipo_reserva", models.CharField(max_length=200)),
                ("nombre_cliente", models.CharField(max_length=200)),
                ("fecha", models.CharField(max_length=200)),
                ("hora", models.CharField(max_length=200)),
            ],
        ),
    ]
