# Generated by Django 4.1 on 2022-11-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labSoft3", "0003_provedores_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reserva", old_name="id_reserva", new_name="telefono",
        ),
        migrations.RemoveField(model_name="reserva", name="tipo_reserva",),
        migrations.AlterField(
            model_name="reserva",
            name="id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
