# Generated by Django 4.1 on 2022-11-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labSoft3", "0005_alter_reserva_id"),
    ]

    operations = [
        migrations.DeleteModel(name="reserva",),
    ]
