# Generated by Django 4.1 on 2022-11-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labSoft3", "0007_reserva"),
    ]

    operations = [
        migrations.DeleteModel(name="reserva",),
    ]
