# Generated by Django 4.1 on 2022-11-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labSoft3", "0011_reserva"),
    ]

    operations = [
        migrations.RemoveField(model_name="reserva", name="hora",),
        migrations.RemoveField(model_name="reserva", name="id_reserva",),
        migrations.RemoveField(model_name="reserva", name="numero_mesa",),
        migrations.RemoveField(model_name="reserva", name="tipo_reserva",),
    ]
