# Generated by Django 4.1 on 2022-11-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labSoft3", "0012_remove_reserva_hora_remove_reserva_id_reserva_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="numero_personas",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="telefono",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="fecha",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="nombre_cliente",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
